### ISSUE TITLE
`throttle` signal not updated

### ISSUE THREAD

**Issue by skleinbo** [JuliaGizmos/Reactive.jl#123]
Reactive: 0.3.7
Julia: 0.5.0

Maybe I am misunderstanding how `throttle` works, but I would expect the following code to print a line every second

```julia
using Reactive

x=fps(15)
y=throttle(1.0, x)
preserve(map(println, y))
```

Nothing happens though. `y` is not updated with `x`. Note that printing `x` directly works perfectly.

So, what's going on, or what is it I do not understand?

Thank you!

**Comment by JobJob** [comment]
The current implementation of `throttle` is that it won't "fire" until `dt` (first argument) seconds have passed since it was last "pushed" to. So, what's happening is, since `x` never stops "pushing" to it (it's pushing every ~1/15 secs), 1.0 secs never goes by before it gets "pushed" to again, which restarts the 1.0 second timer, and thus it never "fires". 

It's more like underscore.js's [debounce](http://underscorejs.org/#debounce) if that helps.

I'm not sure whether that's ideal, but that's the current state of play. There might well be another way to achieve what you want with some combination of `fps(1.0)`,  `sampleon` and possibly `foldp` if you want to give more details.

**Comment by skleinbo** [comment]
@JobJob 
Thank you. That clears it up for me! I would still argue that `throttle` is a bit misleading. And so is the doctring.

But for my immediate usecase, combining `fps` and `sampleon` will do perfectly fine.

May be closed.

**Comment by JobJob** [comment]
You now have a throttle that behaves as you would expect on master. The old throttle behaviour is retained in `debounce`. See `?throttle` and `?debounce` for more info.
